export const CACHE_GROUP_IDS = Object.freeze({
  tournamentDetail: "tournamentDetail",
  tournamentBrackets: "tournamentBrackets",
  tournamentBracketMatches: "tournamentBracketMatches",
  tournamentScheduleMatches: "tournamentScheduleMatches",
  courtDetails: "courtDetails",
  overlayMatch: "overlayMatch",
  overlayNextCourt: "overlayNextCourt",
  liveMatches: "liveMatches",
  liveAppBootstrap: "liveAppBootstrap",
  liveAppCourtRuntime: "liveAppCourtRuntime",
  liveAppMatchRuntime: "liveAppMatchRuntime",
  adminTournamentCourts: "adminTournamentCourts",
  configValues: "configValues",
  weatherKit: "weatherKit",
  publicHome: "publicHome",
  publicOverlayConfig: "publicOverlayConfig",
  cmsHero: "cmsHero",
  cmsContact: "cmsContact",
  newsList: "newsList",
  newsDetail: "newsDetail",
});
