source "https://cdn.cocoapods.org/"

platform :ios, "15.1"
use_frameworks!
inhibit_all_warnings!

target "PickleTourLive" do
  pod "AppAuth", "~> 1.7"
  pod "Socket.IO-Client-Swift", "~> 16.1"
  pod "HaishinKit", "~> 1.6"
  pod "FirebaseCore"
  pod "FirebaseCrashlytics"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "15.1"
      config.build_settings["SWIFT_VERSION"] = "5.0"

      if target.name == "HaishinKit" && config.name == "Release"
        # Work around a Swift optimizer crash when archiving HaishinKit on Xcode 17.
        config.build_settings["SWIFT_OPTIMIZATION_LEVEL"] = "-Onone"
        config.build_settings["SWIFT_COMPILATION_MODE"] = "singlefile"
      end
    end
  end
end
