const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("api", {
  envCheck: () => ipcRenderer.invoke("env-check"),
  sysStats: () => ipcRenderer.invoke("sys-stats"),
  recordsDirGet: () => ipcRenderer.invoke("records-dir-get"),
  recordsDirPick: () => ipcRenderer.invoke("records-dir-pick"),
  recordsDirReset: () => ipcRenderer.invoke("records-dir-reset"),
  recordsDirOpen: () => ipcRenderer.invoke("records-dir-open"),
  // Điều khiển từ xa
  controlGet: () => ipcRenderer.invoke("control-get"),
  controlEnable: (enabled) => ipcRenderer.invoke("control-enable", { enabled }),
  controlRegenPin: () => ipcRenderer.invoke("control-regen-pin"),
  onRemoteCmd: (cb) => ipcRenderer.on("remote-cmd", (_e, m) => cb(m)),
  remoteReply: (m) => ipcRenderer.send("remote-reply", m),
  login: (args) => ipcRenderer.invoke("login", args),
  get: (args) => ipcRenderer.invoke("api-get", args),
  req: (args) => ipcRenderer.invoke("api-req", args),
  start: (args) => ipcRenderer.invoke("start", args),
  stop: (args) => ipcRenderer.invoke("stop", args),
  // Hẹn giờ bắt đầu live
  toggleDelogo: (args) => ipcRenderer.invoke("toggle-delogo", args),
  scheduleAdd: (args) => ipcRenderer.invoke("schedule-add", args),
  scheduleList: () => ipcRenderer.invoke("schedule-list"),
  scheduleCancel: (id) => ipcRenderer.invoke("schedule-cancel", { id }),
  onScheduleFired: (cb) => ipcRenderer.on("schedule-fired", (_e, p) => cb(p)),
  onScheduleStarted: (cb) => ipcRenderer.on("schedule-started", (_e, p) => cb(p)),
  onScheduleError: (cb) => ipcRenderer.on("schedule-error", (_e, p) => cb(p)),
  previewStart: (args) => ipcRenderer.invoke("preview-start", args),
  previewStop: () => ipcRenderer.invoke("preview-stop"),
  directStart: (args) => ipcRenderer.invoke("direct-start", args),
  directStop: () => ipcRenderer.invoke("direct-stop"),
  randomStart: (args) => ipcRenderer.invoke("random-start", args),
  randomStop: () => ipcRenderer.invoke("random-stop"),
  matchScore: (args) => ipcRenderer.invoke("match-score", args),
  previewLog: () => ipcRenderer.invoke("preview-log"),
  previewOpenLog: () => ipcRenderer.invoke("preview-openlog"),
  onPreviewExit: (cb) => ipcRenderer.on("preview-exit", (_e, p) => cb(p)),
  openExternal: (url) => ipcRenderer.invoke("open-external", url),
  openLog: (sid) => ipcRenderer.invoke("open-log", sid),
  onWorkerExit: (cb) => ipcRenderer.on("worker-exit", (_e, p) => cb(p)),
  onPerMatch: (cb) => ipcRenderer.on("per-match", (_e, p) => cb(p)),
  onRecUpload: (cb) => ipcRenderer.on("rec-upload", (_e, p) => cb(p)),
  // Tự setup Python lần đầu (tạo venv + cài Imou) ngay trong app.
  setupPython: () => ipcRenderer.invoke("setup-python"),
  onSetupProgress: (cb) => ipcRenderer.on("setup-progress", (_e, m) => cb(m)),
});
