const baseTextStyle = {
  fontFamily: "Montserrat, Arial, sans-serif",
  fontSize: 40,
  fontWeight: 800,
  color: "#ffffff",
  background: "transparent",
  borderColor: "transparent",
  borderWidth: 0,
  borderRadius: 0,
  textAlign: "left",
  lineHeight: 1.1,
};

const textLayer = ({
  id,
  label,
  binding,
  text,
  x,
  y,
  width,
  height,
  fontSize = 40,
  fontWeight = 800,
  color = "#ffffff",
  textAlign = "left",
  zIndex = 10,
}) => ({
  id,
  type: "text",
  label,
  binding,
  text,
  x,
  y,
  width,
  height,
  zIndex,
  visible: true,
  style: {
    ...baseTextStyle,
    fontSize,
    fontWeight,
    color,
    textAlign,
  },
});

const rectLayer = ({
  id,
  label,
  x,
  y,
  width,
  height,
  background,
  borderColor = "rgba(255,255,255,0.16)",
  borderWidth = 1,
  borderRadius = 22,
  zIndex = 0,
}) => ({
  id,
  type: "rect",
  label,
  binding: "static",
  text: "",
  x,
  y,
  width,
  height,
  zIndex,
  visible: true,
  style: {
    background,
    borderColor,
    borderWidth,
    borderRadius,
  },
});

const serveIndicatorLayer = ({
  id,
  label,
  side = "A",
  x,
  y,
  width = 30,
  height = 30,
  color = "#22c55e",
  zIndex = 30,
}) => {
  const normalizedSide = String(side).toUpperCase() === "B" ? "B" : "A";
  return {
    id,
    type: "serveIndicator",
    label,
    binding: "serve.side",
    text: "",
    x,
    y,
    width,
    height,
    zIndex,
    visible: true,
    visibleWhen: { binding: "serve.side", equals: normalizedSide },
    style: {
      color,
      background: "transparent",
      borderColor: "transparent",
      borderWidth: 0,
      borderRadius: 999,
    },
  };
};

export const overlaySystemTemplates = [
  {
    id: "local-corner-pro",
    key: "corner-pro",
    name: "Góc trái chuyên nghiệp",
    description: "Bảng điểm gọn ở góc trái.",
    isSystem: true,
    engine: "safe-layers",
    canvas: { width: 1920, height: 1080 },
    document: {
      background: "transparent",
      layers: [
        rectLayer({
          id: "bg",
          label: "Nền bảng điểm",
          x: 48,
          y: 48,
          width: 820,
          height: 242,
          background: "rgba(7, 12, 20, 0.9)",
        }),
        rectLayer({
          id: "score_band",
          label: "Nền cột điểm",
          x: 720,
          y: 104,
          width: 100,
          height: 140,
          background: "#23865c",
          borderColor: "transparent",
          zIndex: 2,
        }),
        textLayer({
          id: "tournament",
          label: "Tên giải",
          binding: "tournament.name",
          text: "Tên giải đấu",
          x: 78,
          y: 72,
          width: 600,
          height: 34,
          fontSize: 26,
          zIndex: 3,
        }),
        textLayer({
          id: "team_a",
          label: "Đội A",
          binding: "teamA.name",
          text: "Đội A",
          x: 78,
          y: 126,
          width: 600,
          height: 52,
          fontSize: 34,
          zIndex: 3,
        }),
        textLayer({
          id: "team_b",
          label: "Đội B",
          binding: "teamB.name",
          text: "Đội B",
          x: 78,
          y: 190,
          width: 600,
          height: 52,
          fontSize: 34,
          zIndex: 3,
        }),
        textLayer({
          id: "score_a",
          label: "Điểm A",
          binding: "scoreA",
          text: "0",
          x: 720,
          y: 124,
          width: 100,
          height: 52,
          fontSize: 42,
          fontWeight: 900,
          textAlign: "center",
          zIndex: 4,
        }),
        textLayer({
          id: "score_b",
          label: "Điểm B",
          binding: "scoreB",
          text: "0",
          x: 720,
          y: 190,
          width: 100,
          height: 52,
          fontSize: 42,
          fontWeight: 900,
          textAlign: "center",
          zIndex: 4,
        }),
        serveIndicatorLayer({
          id: "serve_a",
          label: "Bóng giao A",
          side: "A",
          x: 678,
          y: 138,
          width: 26,
          height: 26,
        }),
        serveIndicatorLayer({
          id: "serve_b",
          label: "Bóng giao B",
          side: "B",
          x: 678,
          y: 204,
          width: 26,
          height: 26,
        }),
        textLayer({
          id: "round",
          label: "Vòng đấu",
          binding: "match.roundLabel",
          text: "Vòng đấu",
          x: 78,
          y: 250,
          width: 600,
          height: 28,
          fontSize: 22,
          color: "rgba(255,255,255,0.78)",
          zIndex: 3,
        }),
      ],
    },
  },
  {
    id: "local-bottom-tv",
    key: "bottom-tv",
    name: "Thanh dưới kiểu TV",
    description: "Bảng điểm ngang ở cuối màn hình.",
    isSystem: true,
    engine: "safe-layers",
    canvas: { width: 1920, height: 1080 },
    document: {
      background: "transparent",
      layers: [
        rectLayer({
          id: "bg",
          label: "Nền bảng điểm",
          x: 360,
          y: 842,
          width: 1200,
          height: 156,
          background: "rgba(13, 18, 28, 0.92)",
          borderRadius: 18,
        }),
        textLayer({
          id: "team_a",
          label: "Đội A",
          binding: "teamA.name",
          text: "Đội A",
          x: 418,
          y: 884,
          width: 420,
          height: 56,
          textAlign: "right",
        }),
        textLayer({
          id: "score_a",
          label: "Điểm A",
          binding: "scoreA",
          text: "0",
          x: 868,
          y: 864,
          width: 92,
          height: 86,
          fontSize: 70,
          fontWeight: 900,
          textAlign: "center",
        }),
        textLayer({
          id: "score_b",
          label: "Điểm B",
          binding: "scoreB",
          text: "0",
          x: 960,
          y: 864,
          width: 92,
          height: 86,
          fontSize: 70,
          fontWeight: 900,
          color: "#d8f7ff",
          textAlign: "center",
        }),
        textLayer({
          id: "team_b",
          label: "Đội B",
          binding: "teamB.name",
          text: "Đội B",
          x: 1082,
          y: 884,
          width: 420,
          height: 56,
        }),
        serveIndicatorLayer({
          id: "serve_a",
          label: "Bóng giao A",
          side: "A",
          x: 842,
          y: 898,
          width: 28,
          height: 28,
        }),
        serveIndicatorLayer({
          id: "serve_b",
          label: "Bóng giao B",
          side: "B",
          x: 1054,
          y: 898,
          width: 28,
          height: 28,
        }),
        textLayer({
          id: "meta",
          label: "Thông tin trận",
          binding: "match.stageName",
          text: "Thông tin trận",
          x: 438,
          y: 952,
          width: 1044,
          height: 32,
          fontSize: 24,
          color: "rgba(255,255,255,0.72)",
          textAlign: "center",
        }),
      ],
    },
  },
  {
    id: "local-vertical-live",
    key: "vertical-live",
    name: "Dọc cho live mobile",
    description: "Bố cục dọc gọn cho khung quay đứng.",
    isSystem: true,
    engine: "safe-layers",
    canvas: { width: 1920, height: 1080 },
    document: {
      background: "transparent",
      layers: [
        rectLayer({
          id: "bg",
          label: "Nền bảng điểm",
          x: 70,
          y: 120,
          width: 420,
          height: 520,
          background: "rgba(5, 8, 13, 0.9)",
          borderRadius: 28,
        }),
        textLayer({
          id: "round",
          label: "Vòng đấu",
          binding: "match.roundLabel",
          text: "Vòng đấu",
          x: 104,
          y: 162,
          width: 352,
          height: 34,
          fontSize: 24,
          color: "rgba(255,255,255,0.72)",
          textAlign: "center",
        }),
        textLayer({
          id: "team_a",
          label: "Đội A",
          binding: "teamA.name",
          text: "Đội A",
          x: 104,
          y: 240,
          width: 352,
          height: 80,
          fontSize: 40,
          fontWeight: 900,
          textAlign: "center",
        }),
        textLayer({
          id: "score_a",
          label: "Điểm A",
          binding: "scoreA",
          text: "0",
          x: 104,
          y: 332,
          width: 352,
          height: 76,
          fontSize: 72,
          fontWeight: 900,
          color: "#8ee6b8",
          textAlign: "center",
        }),
        textLayer({
          id: "team_b",
          label: "Đội B",
          binding: "teamB.name",
          text: "Đội B",
          x: 104,
          y: 452,
          width: 352,
          height: 80,
          fontSize: 40,
          fontWeight: 900,
          textAlign: "center",
        }),
        textLayer({
          id: "score_b",
          label: "Điểm B",
          binding: "scoreB",
          text: "0",
          x: 104,
          y: 542,
          width: 352,
          height: 76,
          fontSize: 72,
          fontWeight: 900,
          color: "#93c5fd",
          textAlign: "center",
        }),
        serveIndicatorLayer({
          id: "serve_a",
          label: "Bóng giao A",
          side: "A",
          x: 448,
          y: 267,
          width: 28,
          height: 28,
        }),
        serveIndicatorLayer({
          id: "serve_b",
          label: "Bóng giao B",
          side: "B",
          x: 448,
          y: 477,
          width: 28,
          height: 28,
        }),
      ],
    },
  },
];
